### ISSUE TITLE
Couldn't connect to TextMate!

### ISSUE THREAD

**Issue by SymphonyPy** [sclukey/rmate-python#2]
I am using this on Ubuntu and meet this problem.
`root@VM-42-3-ubuntu:~# rmate -p 52698 ping.c`
`Couldn't connect to TextMate!`
It worked when I first used this yesterday, but the error appeared today. 
Is there any way to solve this? Thank you!

**Comment by Kmyu1k** [comment]
Maybe your remote server port is not open.  try to open the port:**52698**.

**Comment by broadtoad** [comment]
rmate also abruptly stopped working for me as well - was working fine before (apart from occasional saving issues).

Tried bash and python version and receive same error: `Couldn't connect to TextMate!`

**Comment by Kmyu1k** [comment]
I found when i restart the sever,the error can be solved.
here is my step:
1. in vscode press F1 and select **Remote:Stop Server**
2. in vscode press F1 and select **Remote:Start Server**

**Comment by salmr0** [comment]
I am having the same issue.  Looks like the socket is left open on the server side.  I quit everything and logged out of everywhere.   Then I ssh back into the server (after disabling the SSH port forwarding of port 52698) and I see this.  There should be no port using 52698 as I disables ssh port forwarding but some how the socket is still there lingering. 

```
netstat -tnl |grep 52698 
tcp        0      0 127.0.0.1:52698         0.0.0.0:*               LISTEN     

```

For me this is why I get the "Couldn't connect to TextMate!" message because the port is in use and I can't get rid of it.  Don't have root access to server so I can't get the PID to kill it.

**Comment by salmr0** [comment]
Got one of the admins(root) to run netstat with "-p" option for me. Looks like some other user is using that port (maybe other rmate user).  That is why I can not use it and get the "Couldn't connect to TextMate!". 

So no issue.  I will just pick a different port. Sorry for the spam.

**Comment by rspeed** [comment]
It seems this can be closed.

**Comment by sclukey** [comment]
I agree

**Comment by nickhir** [comment]
Hello,

I am facting the same problem now... I tried to mimic salmr0 steps but the problem persists... 
I used `netstat -tnl` to identify an unused port, then forwarded that port and used it for rmate (`rmate -p 2269 testfile.txt`) but I still get the `Couldn't connect to TextMate!` message. If I try a random port (i.e. 24587) I get the following error:

```
Traceback (most recent call last):
  File "/rds/user/nh608/hpc-work/software/micromamba/bin/rmate", line 304, in <module>
    main()
  File "/rds/user/nh608/hpc-work/software/micromamba/bin/rmate", line 295, in main
    s = connect_to_tm()
  File "/rds/user/nh608/hpc-work/software/micromamba/bin/rmate", line 103, in connect_to_tm
    raise Exception('Could not connect to textmate: %s' % (os.strerror(error)))
Exception: Could not connect to textmate: Cannot assign requested address
```

I am using `rmate-python version 2016-11-03 (1.0.3)`

Any insights are much appreciated!
